export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const LOAD_SEARCHED_PRODUCTS = 'LOAD_SEARCHED_PRODUCTS';
export const EMPTY_ALL = 'EMPTY_ALL';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const LOAD_PRODUCT_DETAILS = 'LOAD_PRODUCT_DETAILS';
export const EMPTY_DETAILS_PAGE = 'EMPTY_DETAILS_PAGE';
export const LOAD_SAME_CATEGORY_PRODUCTS = 'LOAD_SAME_CATEGORY_PRODUCTS';